name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug secrets
      run: |
        echo "Host: ${{ secrets.EC2_HOST }}"
        echo "Username: ${{ secrets.EC2_USERNAME }}"
        echo "Key length: ${#EC2_SSH_KEY}"
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Navigate to project directory
          cd /home/ubuntu/vb-to-csharp-translator
          
          # Pull latest changes
          git pull origin main
          
          # Stop existing containers
          docker-compose down
          
          # Build and start containers
          docker-compose up -d --build
          
          # Wait for services to be healthy
          sleep 30
          
          # Check if services are running
          echo "Checking service health..."
          curl -f http://localhost:8000/health || echo "Backend health check failed"
          curl -f http://localhost:3000 || echo "Frontend health check failed"
          
          echo "Deployment completed!"
