name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Navigate to project directory
          cd /home/ubuntu/vb-to-csharp-translator
          
          # Stash any local changes and pull latest changes
          git stash
          git pull origin main
          
          # Create .env file if it doesn't exist
          if [ ! -f backend/.env ]; then
            cp backend/env.example backend/.env
            echo "Created backend/.env file"
          fi
          
          # Stop existing containers and clean up
          docker-compose down -v
          docker system prune -f
          docker volume prune -f
          
          # Build and start containers
          docker-compose up -d --build
          
          # Wait for services to be healthy
          sleep 30
          
          # Check if services are running
          echo "Checking service health..."
          curl -f http://localhost:8000/health || echo "Backend health check failed"
          curl -f http://localhost:3000 || echo "Frontend health check failed"
          
          echo "Deployment completed!"
